<a href="https://colab.research.google.com/github/Ramyaasuresh/ISEC6000-SecureDevOps/blob/main/assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [151]:
import pandas as pd
import sqlite3
import numpy as np
from matplotlib import pyplot as plt

In [152]:
! wget https://github.com/PaulHancock/COMP5009_pracs/raw/main/data/Assignment2024.sqlite

--2024-09-24 05:26:06--  https://github.com/PaulHancock/COMP5009_pracs/raw/main/data/Assignment2024.sqlite
Resolving github.com (github.com)... 140.82.114.4
Connecting to github.com (github.com)|140.82.114.4|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/PaulHancock/COMP5009_pracs/main/data/Assignment2024.sqlite [following]
--2024-09-24 05:26:07--  https://raw.githubusercontent.com/PaulHancock/COMP5009_pracs/main/data/Assignment2024.sqlite
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1421312 (1.4M) [application/octet-stream]
Saving to: ‘Assignment2024.sqlite.4’

Assignment2024.sqli 100%[===================>]   1.36M  --.-KB/s    in 0.009s

2024-09-24 05:26:07 (159 MB/s) - ‘Assignment2024.sqlite.4’ saved [1421312/1421312]

In [153]:
con = sqlite3.connect('Assignment2024.sqlite')
train_df = pd.read_sql_query("SELECT * FROM train", con)
test_df = pd.read_sql_query("SELECT * FROM test", con)

In [154]:
train_df.head()

,index,System,Science,Method,People,Estate,Tennis,Problem,Buyer,Insect,...,Moment,Driver,Session,Guitar,Shopping,Trainer,Office,Country,Tension,class
0,0,-12.277367,-2.125027,-1.264999,0.854478,2.705232,-92.590128,68.860620,11.426538,-1.215241,...,-34.114437,-83.875566,0,UKBF,-18.883847,220,NaN,51.844775,25.933900,2
1,1,-15.915018,-6.179856,-5.546974,0.685782,-5.639822,-41.829855,112.661676,-5.022515,-286.623875,...,-8046.151876,31.033599,0,SCXP,50.945979,-441,NaN,96.531426,-38.254764,2
2,2,-14.271594,7.301318,11.250151,1.162530,3.394609,-17.046542,102.944428,11.558543,-0.047253,...,-1.326493,17.453811,1,ITVQ,22.305993,-156,NaN,27.276191,2.785682,2
3,3,8.457836,4.288695,-1.506822,1.612383,0.133044,-26.997285,45.890959,1.902642,-0.701772,...,-19.700260,-28.635840,1,ITVQ,36.155249,202,-0.065895,-113.871227,57.827242,1
4,4,-3.065723,-0.328456,7.612236,1.585490,1.161368,9.162676,-23.006553,-3.355169,-0.107726,...,-3.024095,-4.793964,0,JGMQ,-54.292301,-496,NaN,37.558166,34.614522,2

In [155]:
print("Column Names")
print(train_df.columns)
print()
print("Data types")
print(train_df.dtypes)

Column Names
Index(['index', 'System', 'Science', 'Method', 'People', 'Estate', 'Tennis',
       'Problem', 'Buyer', 'Insect', 'Music', 'Guidance', 'Power', 'Knowledge',
       'Owner', 'Oven', 'Storage', 'Resource', 'Writer', 'Member', 'Cookie',
       'Virus', 'Moment', 'Driver', 'Session', 'Guitar', 'Shopping', 'Trainer',
       'Office', 'Country', 'Tension', 'class'],
      dtype='object')

Data types
index          int64
System       float64
Science      float64
Method       float64
People       float64
Estate       float64
Tennis       float64
Problem      float64
Buyer        float64
Insect       float64
Music         object
Guidance     float64
Power        float64
Knowledge      int64
Owner          int64
Oven         float64
Storage       object
Resource     float64
Writer       float64
Member       float64
Cookie       float64
Virus        float64
Moment       float64
Driver       float64
Session        int64
Guitar        object
Shopping     float64
Trainer        int64
Office       float64
Country      float64
Tension      float64
class          int64
dtype: object

In [156]:
train_df.shape

(5000, 32)

In [192]:
train_df.describe()

,index,System,Science,Method,People,Estate,Problem,Buyer,Insect,Guidance,...,Cookie,Virus,Moment,Driver,Session,Shopping,Trainer,Country,Tension,class
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,...,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,2499.500000,3.626589,-0.200416,-2.183269,3.368851,-0.018640,14.866064,2.400767,-0.852966,-20.346725,...,3.094089,0.620706,-23.944606,0.220428,0.507000,-0.994021,-2.712600,0.105429,0.516781,1.390200
std,1443.520003,21.065750,4.251185,12.623537,1.940520,2.772808,81.075291,9.627286,26.960794,39.983065,...,17.972621,3.385152,756.847784,53.170916,0.500001,62.490978,415.315616,98.484851,45.649761,0.666058
min,0.000000,-86.155943,-14.668196,-42.371814,0.001222,-11.278285,-315.530250,-30.200623,-680.429490,-160.260014,...,-73.505481,-13.174394,-19101.126887,-199.363999,0.000000,-225.192995,-1384.000000,-318.860017,-162.342203,0.000000
25%,1249.750000,-10.474370,-3.093249,-11.145639,1.703760,-1.827719,-39.701486,-4.438753,-2.053086,-46.575190,...,-8.936395,-1.657664,-57.634569,-34.532060,0.000000,-42.853643,-285.250000,-65.329902,-30.230250,1.000000
50%,2499.500000,4.130533,-0.159076,-2.493639,3.369625,0.087766,15.547347,1.962666,-0.624693,-21.264337,...,3.524038,0.649151,-17.536472,0.186284,1.000000,-0.374828,-4.000000,1.142042,0.707517,1.000000
75%,3749.250000,18.201192,2.808483,6.491201,5.051381,1.885154,69.221814,8.940031,0.871441,6.304193,...,15.528672,2.890232,24.463230,35.744003,1.000000,40.900158,277.000000,65.544375,31.348482,2.000000
max,4999.000000,79.522878,12.536525,45.130450,6.722135,10.174718,284.982328,38.678186,823.816883,132.889894,...,67.846363,11.898921,23126.321028,213.945884,1.000000,207.901162,1498.000000,346.422286,219.393845,2.000000

In [193]:
train_df.duplicated().sum()

0

In [194]:
def missing(train_df):
  """
  For each attribute/column in the dataframe `df`, count the number of missing entries.
  Return a list of all the coulmns with more than 80% missing entries.
  """
  missing_dict = dict()
  total = train_df.shape[0] # shape[0] is the number of rows
  for attribute in train_df.columns:
    missing = train_df[attribute].isna().sum() # count the number of Null/nan/na values
    frac = missing/total * 100 # as a percentage
    missing_dict[attribute] = frac
  return missing_dict

In [195]:
m_dict = missing(train_df)
m_dict

{'index': 0.0,
 'System': 0.0,
 'Science': 0.0,
 'Method': 0.0,
 'People': 0.0,
 'Estate': 0.0,
 'Problem': 0.0,
 'Buyer': 0.0,
 'Insect': 0.0,
 'Music': 0.0,
 'Guidance': 0.0,
 'Power': 0.0,
 'Knowledge': 0.0,
 'Owner': 0.0,
 'Storage': 0.0,
 'Resource': 0.0,
 'Writer': 0.0,
 'Member': 0.0,
 'Cookie': 0.0,
 'Virus': 0.0,
 'Moment': 0.0,
 'Driver': 0.0,
 'Session': 0.0,
 'Guitar': 0.0,
 'Shopping': 0.0,
 'Trainer': 0.0,
 'Country': 0.0,
 'Tension': 0.0,
 'class': 0.0}

In [196]:
# Look at each attribute/frac pair in the dict and choose those with a frac that is >20
cols_to_drop = [ att for att,frac in m_dict.items() if frac >20]
cols_to_drop

[]

In [190]:
print("Current Columns in train_df:")
print(train_df.columns.tolist())

Current Columns in train_df:
['index', 'System', 'Science', 'Method', 'People', 'Estate', 'Problem', 'Buyer', 'Insect', 'Music', 'Guidance', 'Power', 'Knowledge', 'Owner', 'Storage', 'Resource', 'Writer', 'Member', 'Cookie', 'Virus', 'Moment', 'Driver', 'Session', 'Guitar', 'Shopping', 'Trainer', 'Country', 'Tension', 'class']

In [168]:
cols_to_drop = ['Office']
# Drop the specified column
train_df.drop(columns=cols_to_drop, inplace=True)  # Use 'columns' to specify the list
  # Ensure correct case

In [175]:
cols_to_drop = ['Tennis']
# Drop the specified column
train_df.drop(columns=cols_to_drop, inplace=True)  # Use 'columns' to specify the list
  # Ensure correct case

In [198]:
train_df.columns

Index(['index', 'System', 'Science', 'Method', 'People', 'Estate', 'Problem',
       'Buyer', 'Insect', 'Music', 'Guidance', 'Power', 'Knowledge', 'Owner',
       'Storage', 'Resource', 'Writer', 'Member', 'Cookie', 'Virus', 'Moment',
       'Driver', 'Session', 'Guitar', 'Shopping', 'Trainer', 'Country',
       'Tension', 'class'],
      dtype='object')

In [200]:
dups = train_df.duplicated()
dups

0       False
1       False
2       False
3       False
4       False
        ...
4995    False
4996    False
4997    False
4998    False
4999    False
Length: 5000, dtype: bool

In [205]:
# recall that true = 1, false = 0
dups.sum()

0

In [209]:
# Look at each attribute/frac pair in the dict and choose those with a frac that is <5
cols_to_impute = [ att for att,frac in m_dict.items() if frac >20]
cols_to_impute

[]

In [217]:
for col in cols_to_impute:
  # compute the mean
  mean = ar_df[col].mean()
  # now use the fillna function to replace the NaN avalues with the mean value
  ar_df[col].fillna(mean, inplace=True)

In [218]:
m_dict = missing(train_df)
for col in cols_to_impute:
  print(col, "missing data", m_dict[col])